import type { StorybookConfig } from '@storybook/vue3-vite'
import { fileURLToPath } from 'node:url'
import Vue from '@vitejs/plugin-vue'
import Unocss from 'unocss/vite'
import { mergeConfig } from 'vite'

const config: StorybookConfig = {
  // Stories are co-located next to each component in the package; the Overview
  // is a single MDX page that references all the others via doc blocks.
  stories: [
    '../../packages/design/components/**/*.mdx',
    '../../packages/design/components/**/*.stories.@(ts|js)',
  ],
  addons: ['@storybook/addon-docs'],
  framework: {
    name: '@storybook/vue3-vite',
    // Disable Storybook's Vue docgen: it matches `.js` and re-parses our
    // plugin-vue-compiled package output (→ "missing end tag"). We don't rely
    // on autogenerated prop tables here.
    options: { docgen: false },
  },
  async viteFinal(base) {
    return mergeConfig(base, {
      // `@antfu/design` ships raw `.ts`/`.vue`. Add an explicit plugin-vue to
      // compile the package's SFCs (Storybook's own pipeline only docgen-scans
      // them) and exclude the package from esbuild dep pre-bundling.
      plugins: [
        Vue(),
        Unocss({ configFile: fileURLToPath(new URL('../uno.config.ts', import.meta.url)) }),
      ],
      optimizeDeps: { exclude: ['@antfu/design'] },
    })
  },
}

export default config
